name: Keepalive Workflow
on:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sundays

permissions:
  actions: write

jobs:
  keepalive:
    name: Keep Repositories Active
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Keep workflows alive
        uses: gautamkrishnar/keepalive-workflow@v2
        with:
          workflow_files: "targeting30.yml, targeting7.yml, targeting90.yml, info.yml"
