name: "Meta Targeting 30"
on:
  schedule:
    - cron: '0 1,4,9,12,15,18,21 * * *'
  push:
    branches:
      - main

jobs:
  update-meta-targeting:
    name: Update Meta Targeting
    runs-on: ubuntu-latest # Run directly on the GitHub VM for better stability
    
    strategy:
      matrix:
        iso-code: ["AT"]
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}      
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      TELEGRAM_BOT_ID: ${{ secrets.TELEGRAM_BOT_ID }}
      TELEGRAM_GROUP_ID: ${{ secrets.TELEGRAM_GROUP_ID }}
      WHO_TARGETS_TOKEN: ${{ secrets.WHO_TARGETS_TOKEN }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10" # You can specify a Python version here

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a recent LTS version of Node.js
      
      - name: Install System Dependencies
        run: |
          # Install legacy OpenSSL 1.1 for the 'arrow' R package
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          rm libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          # Install xvfb for headless browser display
          sudo apt-get update && sudo apt-get install -y xvfb
          
      - name: Create and configure Conda environment
        shell: bash -l {0}
        run: |
          conda create -n r-reticulate python=3.10 -y
          conda activate r-reticulate
          python -m pip install --upgrade pip
          python -m pip install playwright xvfbwrapper
          
      - name: Install Playwright Browsers (Official Method)
        run: npx playwright install --with-deps firefox

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          needs: |
            any::tidyverse, any::httr, any::remotes, any::shiny, any::scales,
            any::treemap, any::here, any::jsonlite, any::janitor, any::quarto,
            any::highcharter, any::lubridate, any::gt, any::gtExtras, any::pacman,
            any::openxlsx, any::sf, any::xml2, any::rvest, any::reticulate,
            any::fs, any::countrycode, any::progress, any::cli, any::digest,
            any::glue, any::vroom, any::prettydoc, any::DT, any::piggyback,
            any::httr2, any::openssl, any::arrow

      - name: "Script - Meta Run for ${{ matrix.iso-code }}"
        shell: bash -l {0}
        run: |
          conda activate r-reticulate
          Rscript 'get_audiences.R' "30" "${{ matrix.iso-code }}"