name: "Meta Targeting 30"
on:
  schedule:
    - cron: '0 1,4,9,12,15,18,21 * * *'
  push:
    branches:
      - main

jobs:
  update-meta-targeting:
    name: Update Meta Targeting
    runs-on: ubuntu-latest
    
    # Use a modern R container to support new packages
    container: rocker/r-ver:4.3.3
    
    strategy:
      matrix:
        iso-code: ["AD", "AE", "AG", "AI", "AL", "AM", "AO", "AR", "AT", "AU", 
                   "AZ", "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BM", 
                   "BN", "BO", "BR", "BS", "BT", "BW", "BY", "BZ", "CA", "CD", "CF", 
                   "CG", "CH", "CI", "CL", "CM", "CO", "CR", "CV", "CY", "CZ", "DE", 
                   "DJ", "DK", "DM", "DO", "DZ", "EC", "EE", "EG", "ER", "ES", "ET", 
                   "FI", "FJ", "FK", "FM", "FR", "GA", "GB", "GD", "GE", "GG", "GH", 
                   "GI", "GM", "GN", "GQ", "GR", "GT", "GW", "GY", "HN", "HR", "HT", 
                   "HU", "ID", "IE", "IL", "IM", "IN", "IQ", "IS", "IT", "JE", "JM", 
                   "JO", "JP", "KE", "KG", "KH", "KI", "KM", "KN", "KW", "KY", "KZ", 
                   "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LT", "LU", "LV", "LY", 
                   "MA", "MC", "MD", "ME", "MG", "MH", "MK", "ML", "MM", "MN", "MR", 
                   "MS", "MT", "MU", "MV", "MW", "MX", "MY", "MZ", "NA", "NE", "NG", 
                   "NI", "NL", "NO", "NP", "NR", "NZ", "OM", "PA", "PE", "PG", "PH", 
                   "PK", "PL", "PS", "PT", "PW", "PY", "QA", "RO", "RS", "RW", "SA", 
                   "SB", "SC", "SE", "SG", "SH", "SI", "SK", "SL", "SM", "SN", "SO", 
                   "SR", "SS", "ST", "SV", "SZ", "TC", "TD", "TG", "TH", "TJ", "TM", 
                   "TN", "TO", "TR", "TT", "TV", "TW", "TZ", "UA", "UG", "US", "UY", 
                   "UZ", "VC", "VE", "VG", "VI", "VN", "VU", "WF", "WS", "YE", "YT", 
                   "ZA", "ZM", "ZW", "XK", "HK", "TL", "KR"]
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}      
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      TELEGRAM_BOT_ID: ${{ secrets.TELEGRAM_BOT_ID }}
      TELEGRAM_GROUP_ID: ${{ secrets.TELEGRAM_GROUP_ID }}
      WHO_TARGETS_TOKEN: ${{ secrets.WHO_TARGETS_TOKEN }}
      # NEW: Explicitly tell R's 'reticulate' package which Python to use.
      # This ensures playwrightr finds the Python module we already installed.
      RETICULATE_PYTHON: /usr/bin/python3      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install All System Dependencies
        run: |
          apt-get update
          
          # Install dependencies for Python compilation, arrow, and other packages
          # This is the key fix that allows reticulate::install_python() to work correctly.
          apt-get install -y --no-install-recommends \
            wget \
            libssl-dev \
            libffi-dev \
            libbz2-dev \
            liblzma-dev \
            libncurses-dev \
            libreadline-dev \
            libsqlite3-dev \
            zlib1g-dev \
            build-essential

          # Install legacy OpenSSL 1.1 needed by the arrow R package
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          rm libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          
          # 2. Install Python, pip, AND the venv module for Playwright
          #    The python3-venv package is the critical addition that fixes the error.
          apt-get install -y --no-install-recommends python3 python3-pip python3-venv
          pip3 install playwright
          playwright install --with-deps firefox

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          needs: |
            any::tidyverse
            any::httr
            any::remotes
            any::shiny
            any::scales
            any::treemap
            any::here
            any::jsonlite
            any::janitor
            any::quarto
            any::highcharter
            any::lubridate
            any::gt
            any::gtExtras
            any::pacman
            any::openxlsx
            any::sf
            any::xml2
            any::rvest
            any::reticulate
            any::fs
            any::countrycode
            any::progress
            any::cli
            any::digest
            any::glue
            any::vroom
            any::prettydoc
            any::DT
            any::piggyback
            any::httr2
            any::openssl
            any::arrow

      - name: "Script - Meta Run for ${{ matrix.iso-code }}"
        run: Rscript 'get_audiences.R' "30" "${{ matrix.iso-code }}"