name: "Meta Targeting 7"
on:
  schedule:
    - cron: '0 5,6,7,8,17,18,19,20 * * *'
  push:
    branches:
      - main
      
jobs:
  update-meta-targeting:
    name: Update Meta Targeting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        iso-code: ["AD", "AE", "AG", "AI", "AL", "AM", "AO", "AR", "AT", "AU", 
                   "AZ", "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BM", 
                   "BN", "BO", "BR", "BS", "BT", "BW", "BY", "BZ", "CA", "CD", "CF", 
                   "CG", "CH", "CI", "CL", "CM", "CO", "CR", "CV", "CY", "CZ", "DE", 
                   "DJ", "DK", "DM", "DO", "DZ", "EC", "EE", "EG", "ER", "ES", "ET", 
                   "FI", "FJ", "FK", "FM", "FR", "GA", "GB", "GD", "GE", "GG", "GH", 
                   "GI", "GM", "GN", "GQ", "GR", "GT", "GW", "GY", "HN", "HR", "HT", 
                   "HU", "ID", "IE", "IL", "IM", "IN", "IQ", "IS", "IT", "JE", "JM", 
                   "JO", "JP", "KE", "KG", "KH", "KI", "KM", "KN", "KW", "KY", "KZ", 
                   "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LT", "LU", "LV", "LY", 
                   "MA", "MC", "MD", "ME", "MG", "MH", "MK", "ML", "MM", "MN", "MR", 
                   "MS", "MT", "MU", "MV", "MW", "MX", "MY", "MZ", "NA", "NE", "NG", 
                   "NI", "NL", "NO", "NP", "NR", "NZ", "OM", "PA", "PE", "PG", "PH", 
                   "PK", "PL", "PS", "PT", "PW", "PY", "QA", "RO", "RS", "RW", "SA", 
                   "SB", "SC", "SE", "SG", "SH", "SI", "SK", "SL", "SM", "SN", "SO", 
                   "SR", "SS", "ST", "SV", "SZ", "TC", "TD", "TG", "TH", "TJ", "TM", 
                   "TN", "TO", "TR", "TT", "TV", "TW", "TZ", "UA", "UG", "US", "UY", 
                   "UZ", "VC", "VE", "VG", "VI", "VN", "VU", "WF", "WS", "YE", "YT", 
                   "ZA", "ZM", "ZW", "XK", "HK", "TL", "KR"]
      max-parallel: 5
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
    steps:
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - name: Setup - Checkout repo
        uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          needs: |
            any::tidyverse
            any::httr
            any::remotes
            any::shiny
            any::scales
            any::treemap
            any::here
            any::jsonlite
            any::janitor
            any::quarto
            any::highcharter
            any::lubridate
            any::gt
            any::gtExtras
            any::pacman
            any::openxlsx
            any::sf
            any::xml2
            any::rvest
            any::reticulate
            any::fs
            any::countrycode
            any::progress
            any::cli
            any::digest
            any::glue
            any::vroom
            any::prettydoc
            any::DT
            any::piggyback
            any::arrow
      - name: Apt-get update things
        run: |
          sudo apt-get update 
      - name: Apt-get needed things
        run: |
          sudo apt-get install --no-install-recommends -y \
          libssl-dev \
          libcurl4-openssl-dev \
          libxml2-dev \
          libharfbuzz-dev \
          libfribidi-dev
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: "Script - Meta Run for ${{ matrix.iso-code }}"
        run: Rscript 'get_audiences.R' "7" "${{ matrix.iso-code }}"